name: apicloudflax

services:
  app:
    container_name: apicloudflax-app
    image: apicloudflax-app
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ..:/app
      - go-mod-cache:/go/pkg/mod
      - ~/.aws:/root/.aws
    env_file:
      - ../.env
    restart: unless-stopped

volumes:
  go-mod-cache:
    name: apicloudflax-app-cache

networks:
  default:
    name: apicloudflax
